apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: app1
  labels:
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: us-central1-docker.pkg.dev/crack-celerity-353014/sharky-app1/app1:latest
        ports:
        - containerPort: 8080
